-- Update stays table to add status fields
ALTER TABLE stays ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'upcoming';
ALTER TABLE stays ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) NOT NULL DEFAULT 'pending';
ALTER TABLE stays ADD COLUMN IF NOT EXISTS number_of_guests INTEGER NOT NULL DEFAULT 1;
ALTER TABLE stays ADD COLUMN IF NOT EXISTS special_requests TEXT;
ALTER TABLE stays ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW(); 